name: wizardry
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - spyder
  - numpy
  - matplotlib
  - pandas
  - scipy
  - statsmodels
  - jupyterlab
  - ipykernel
  - ipywidgets
  - notebook
  - openpyxl
  - seaborn
  - plotly